# Generated by Django 5.2.6 on 2025-09-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='profession',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='profession',
            index=models.Index(fields=['-time_create'], name='mainpage_pr_time_cr_2a0d91_idx'),
        ),
    ]
