# Generated by Django 5.2.6 on 2025-09-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_profession_options_profession_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
