# Generated by Django 5.2.6 on 2025-09-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_profession_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
