# Generated by Django 5.2.6 on 2025-09-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_category_profession_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.category'),
        ),
    ]
