# Generated by Django 5.2.6 on 2025-11-12 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_category_options_alter_profession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_type', models.CharField(choices=[('default1', 'Аватар 1'), ('default2', 'Аватар 2'), ('default3', 'Аватар 3'), ('default4', 'Аватар 4'), ('default5', 'Аватар 5'), ('custom', 'Своя аватарка')], default='default1', max_length=10)),
                ('custom_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/custom/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
