# Generated by Django 5.2.6 on 2025-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_category_options_alter_profession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('experience', models.CharField(choices=[('noExperience', 'Нет опыта'), ('between1And3', 'От 1 года до 3 лет'), ('between3And6', 'От 3 до 6 лет'), ('moreThan6', 'Более 6 лет')], max_length=20)),
                ('employment', models.CharField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('project', 'Проектная работа'), ('volunteer', 'Волонтерство'), ('probation', 'Стажировка')], max_length=20)),
                ('schedule', models.CharField(choices=[('fullDay', 'Полный день'), ('shift', 'Сменный график'), ('flexible', 'Гибкий график'), ('remote', 'Удаленная работа'), ('flyInFlyOut', 'Вахтовый метод')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('salary_from', models.IntegerField(blank=True, null=True)),
                ('salary_to', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('key_skills', models.TextField(blank=True)),
                ('is_junior', models.BooleanField(default=False)),
                ('search_query', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
    ]
