# Generated by Django 5.2.6 on 2025-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='custom_avatar',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_type',
            field=models.CharField(choices=[('men', 'Мужская аватарка'), ('girl', 'Женская аватарка')], default='men', max_length=10),
        ),
    ]
