# Generated by Django 5.2.6 on 2025-11-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_vacancy'),
        ('mainpage', '0009_remove_userprofile_custom_avatar_and_more'),
    ]

    operations = [
    ]
